"use strict";

const ON = true;
const OFF = false;

module.exports = {
  extends: "tslint-sonarts",
  rules: {
    // Bugs
    "no-all-duplicated-branches": ON,
    "no-case-with-or": ON,
    "no-collection-size-mischeck": ON,
    "no-element-overwrite": ON,
    "no-empty-destructuring": ON,
    "no-identical-conditions": ON,
    "no-identical-expressions": ON,
    "no-ignored-initial-value": ON,
    "no-ignored-return": ON,
    "no-in-misuse": ON,
    "no-misleading-array-reverse": ON,
    "no-misspelled-operator": ON,
    "no-self-assignment": ON,
    "no-try-promise": ON,
    "no-unthrown-error": ON,
    "no-use-of-empty-return-value": ON,
    "no-useless-increment": ON,
    "no-useless-intersection": ON,

    // Code Smell
    "arguments-order": ON,
    "bool-param-default": ON,
    "cognitive-complexity": ON,
    "consecutive-overloads": ON,
    "max-switch-cases": [ON, 20],
    "max-union-size": [ON, 10],
    "mccabe-complexity": [ON, 20],
    "no-accessor-field-mismatch": ON,
    "no-alphabetical-sort": ON,
    "no-array-delete": ON,
    "no-big-function": [ON, 300],
    "no-commented-code": ON,
    "no-dead-store": ON,
    "no-duplicate-in-composite": ON,
    "no-duplicate-string": [ON, 5],
    "no-duplicated-branches": ON,
    "no-empty-nested-blocks": ON,
    "no-extra-semicolon": ON,
    "no-gratuitous-expressions": ON,
    "no-hardcoded-credentials": [ON, "password", "secret", "token"],
    "no-identical-functions": ON,
    "no-inconsistent-return": ON,
    "no-invalid-await": ON,
    "no-invariant-return": ON,
    "no-inverted-boolean-check": ON,
    "no-multiline-string-literals": ON,
    "no-nested-incdec": ON,
    "no-nested-switch": ON,
    "no-nested-template-literals": OFF,
    "no-redundant-boolean": ON,
    "no-redundant-jump": ON,
    "no-redundant-parentheses": ON,
    "no-return-type-any": ON,
    "no-same-line-conditional": ON,
    "no-small-switch": ON,
    "no-statements-same-line": ON,
    "no-unconditional-jump": ON,
    "no-unenclosed-multiline-block": ON,
    "no-unused-array": ON,
    "no-useless-cast": ON,
    "no-useless-catch": ON,
    "no-variable-usage-before-declaration": ON,
    "parameters-max-number": [ON, 10],
    "prefer-default-last": ON,
    "prefer-immediate-return": ON,
    "prefer-optional": ON,
    "prefer-promise-shorthand": ON,
    "prefer-type-guard": OFF,
    "use-primitive-type": ON,
    "use-type-alias": ON
  }
};
